<p><b>[WARN]</b>&nbsp;Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1078fa890>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session</p><p><b>[WARN]</b>&nbsp;Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1078fabc0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session</p><p><b>[WARN]</b>&nbsp;Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1078fabf0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session</p><p style="color: red"><b>[FAIL]</b>&nbsp;MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1078fb1c0>: Failed to establish a new connection: [Errno 61] Connection refused'))</p>